import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { motion } from 'framer-motion';
import { Heart, Smile, Meh, Frown, Plus } from 'lucide-react';
const emotions = [
    { id: 1, type: 'joy', intensity: 8, time: '09:30', trigger: 'Completed morning workout' },
    { id: 2, type: 'stress', intensity: 6, time: '11:45', trigger: 'Difficult client meeting' },
    { id: 3, type: 'gratitude', intensity: 9, time: '14:20', trigger: 'Team appreciation message' },
    { id: 4, type: 'anxiety', intensity: 4, time: '16:15', trigger: 'Upcoming presentation' }
];
const emotionIcons = {
    joy: { icon: Smile, color: 'text-emerald-400' },
    stress: { icon: Frown, color: 'text-red-400' },
    gratitude: { icon: Heart, color: 'text-pink-400' },
    anxiety: { icon: Meh, color: 'text-amber-400' }
};
export function EmotionLog() {
    const [showAddForm, setShowAddForm] = useState(false);
    return (_jsxs(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, className: "glass-card rounded-xl p-6", children: [_jsxs("div", { className: "flex items-center justify-between mb-6", children: [_jsx("h3", { className: "text-xl font-semibold text-white", children: "Emotion Log" }), _jsxs("button", { onClick: () => setShowAddForm(true), className: "flex items-center space-x-2 px-3 py-1.5 bg-purple-600 hover:bg-purple-700 rounded-lg transition-colors", children: [_jsx(Plus, { className: "w-4 h-4 text-white" }), _jsx("span", { className: "text-white text-sm", children: "Log Emotion" })] })] }), _jsx("div", { className: "space-y-4", children: emotions.map((emotion, index) => {
                    const EmotionIcon = emotionIcons[emotion.type].icon;
                    const iconColor = emotionIcons[emotion.type].color;
                    return (_jsx(motion.div, { initial: { opacity: 0, x: 20 }, animate: { opacity: 1, x: 0 }, transition: { delay: 0.1 + index * 0.1 }, className: "p-4 bg-slate-800/30 rounded-lg", children: _jsxs("div", { className: "flex items-start space-x-3", children: [_jsx("div", { className: "p-2 bg-slate-700/50 rounded-lg", children: _jsx(EmotionIcon, { className: `w-4 h-4 ${iconColor}` }) }), _jsxs("div", { className: "flex-1", children: [_jsxs("div", { className: "flex items-center justify-between mb-2", children: [_jsx("h4", { className: "text-sm font-medium text-white capitalize", children: emotion.type }), _jsx("span", { className: "text-xs text-slate-400", children: emotion.time })] }), _jsx("p", { className: "text-sm text-slate-300 mb-2", children: emotion.trigger }), _jsxs("div", { className: "flex items-center space-x-2", children: [_jsx("span", { className: "text-xs text-slate-400", children: "Intensity:" }), _jsx("div", { className: "flex space-x-1", children: [...Array(10)].map((_, i) => (_jsx("div", { className: `w-2 h-2 rounded-full ${i < emotion.intensity ? 'bg-purple-400' : 'bg-slate-600'}` }, i))) }), _jsxs("span", { className: "text-xs text-purple-400", children: [emotion.intensity, "/10"] })] })] })] }) }, emotion.id));
                }) }), _jsx("div", { className: "mt-6 p-3 bg-purple-600/20 rounded-lg", children: _jsx("p", { className: "text-sm text-purple-300", children: "\uD83E\uDDE0 Your emotional patterns show high resilience and self-awareness" }) }), showAddForm && (_jsx(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, className: "fixed inset-0 bg-black/50 flex items-center justify-center z-50", onClick: () => setShowAddForm(false), children: _jsxs("div", { className: "glass-card rounded-xl p-6 w-96 m-4", onClick: (e) => e.stopPropagation(), children: [_jsx("h4", { className: "text-lg font-semibold text-white mb-4", children: "Log Emotion" }), _jsxs("form", { className: "space-y-4", children: [_jsxs("select", { className: "w-full px-3 py-2 bg-slate-800 border border-slate-700 rounded-lg text-white", children: [_jsx("option", { value: "", children: "Select emotion type" }), _jsx("option", { value: "joy", children: "Joy" }), _jsx("option", { value: "stress", children: "Stress" }), _jsx("option", { value: "gratitude", children: "Gratitude" }), _jsx("option", { value: "anxiety", children: "Anxiety" }), _jsx("option", { value: "excitement", children: "Excitement" }), _jsx("option", { value: "sadness", children: "Sadness" })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-sm text-slate-400 mb-2", children: "Intensity (1-10)" }), _jsx("input", { type: "range", min: "1", max: "10", className: "w-full" })] }), _jsx("textarea", { placeholder: "What triggered this emotion?", className: "w-full h-20 p-3 bg-slate-800 border border-slate-700 rounded-lg text-white placeholder-slate-400 resize-none" }), _jsxs("div", { className: "flex space-x-3", children: [_jsx("button", { type: "button", onClick: () => setShowAddForm(false), className: "flex-1 px-4 py-2 bg-slate-700 hover:bg-slate-600 rounded-lg text-white transition-colors", children: "Cancel" }), _jsx("button", { type: "submit", className: "flex-1 px-4 py-2 bg-purple-600 hover:bg-purple-700 rounded-lg text-white transition-colors", children: "Log Emotion" })] })] })] }) }))] }));
}
