import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from 'framer-motion';
import { Trash2, Copy } from 'lucide-react';
import { useCalculatorStore } from '../store/calculatorStore';
export function CalculatorHistory() {
    const { history, clearHistory } = useCalculatorStore();
    const copyToClipboard = (text) => {
        navigator.clipboard.writeText(text);
    };
    return (_jsxs(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { delay: 0.1 }, className: "glass-card rounded-xl p-6", children: [_jsxs("div", { className: "flex items-center justify-between mb-6", children: [_jsx("h3", { className: "text-xl font-semibold text-white", children: "History" }), history.length > 0 && (_jsxs("button", { onClick: clearHistory, className: "flex items-center space-x-2 px-3 py-1.5 bg-red-600 hover:bg-red-700 rounded-lg transition-colors", children: [_jsx(Trash2, { className: "w-4 h-4 text-white" }), _jsx("span", { className: "text-white text-sm", children: "Clear" })] }))] }), history.length === 0 ? (_jsxs("div", { className: "text-center py-8", children: [_jsx("div", { className: "w-16 h-16 bg-slate-800 rounded-full flex items-center justify-center mx-auto mb-4", children: _jsx("span", { className: "text-2xl", children: "\uD83E\uDDEE" }) }), _jsx("p", { className: "text-slate-400 mb-2", children: "No calculations yet" }), _jsx("p", { className: "text-sm text-slate-500", children: "Your calculation history will appear here" })] })) : (_jsx("div", { className: "space-y-3 max-h-96 overflow-y-auto", children: history.map((entry, index) => (_jsx(motion.div, { initial: { opacity: 0, x: 20 }, animate: { opacity: 1, x: 0 }, transition: { delay: index * 0.05 }, className: "p-3 bg-slate-800/30 rounded-lg hover:bg-slate-800/50 transition-colors group", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex-1", children: [_jsx("p", { className: "text-sm text-slate-300 font-mono", children: entry.calculation }), _jsxs("p", { className: "text-lg text-white font-mono", children: ["= ", entry.result] }), _jsx("p", { className: "text-xs text-slate-500", children: new Date(entry.timestamp).toLocaleString() })] }), _jsx("button", { onClick: () => copyToClipboard(entry.result), className: "p-2 opacity-0 group-hover:opacity-100 hover:bg-slate-700 rounded-lg transition-all", title: "Copy result", children: _jsx(Copy, { className: "w-4 h-4 text-slate-400 hover:text-white" }) })] }) }, entry.id))) })), history.length > 0 && (_jsxs("div", { className: "mt-6 p-4 bg-slate-800/30 rounded-lg", children: [_jsx("h4", { className: "text-sm font-medium text-white mb-2", children: "Statistics" }), _jsxs("div", { className: "grid grid-cols-2 gap-4 text-sm", children: [_jsxs("div", { children: [_jsx("span", { className: "text-slate-400", children: "Total Calculations:" }), _jsx("span", { className: "text-white ml-2", children: history.length })] }), _jsxs("div", { children: [_jsx("span", { className: "text-slate-400", children: "Today:" }), _jsx("span", { className: "text-white ml-2", children: history.filter(h => new Date(h.timestamp).toDateString() === new Date().toDateString()).length })] })] })] }))] }));
}
