import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from 'framer-motion';
import { Clock, MapPin, CheckCircle, Circle, Plus } from 'lucide-react';
import { useSpiritualStore } from '../store/spiritualStore';
export function PrayerSchedule() {
    const { prayers, completePrayer } = useSpiritualStore();
    const completedPrayers = prayers.filter(p => p.isCompleted).length;
    const totalPrayers = prayers.length;
    return (_jsxs(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, className: "glass-card rounded-xl p-6", children: [_jsxs("div", { className: "flex items-center justify-between mb-6", children: [_jsxs("div", { className: "flex items-center space-x-3", children: [_jsx(Clock, { className: "w-5 h-5 text-emerald-400" }), _jsx("h3", { className: "text-xl font-semibold text-white", children: "Prayer Schedule" })] }), _jsxs("div", { className: "text-right", children: [_jsxs("p", { className: "text-sm text-emerald-400 font-medium", children: [completedPrayers, "/", totalPrayers, " completed"] }), _jsx("p", { className: "text-xs text-slate-400", children: "Today" })] })] }), _jsx("div", { className: "mb-6", children: _jsx("div", { className: "bg-slate-700 rounded-full h-2", children: _jsx(motion.div, { initial: { width: 0 }, animate: { width: `${(completedPrayers / totalPrayers) * 100}%` }, transition: { duration: 0.8 }, className: "bg-gradient-to-r from-emerald-500 to-emerald-400 h-2 rounded-full" }) }) }), _jsx("div", { className: "space-y-3", children: prayers.map((prayer, index) => (_jsxs(motion.div, { initial: { opacity: 0, x: 20 }, animate: { opacity: 1, x: 0 }, transition: { delay: 0.1 + index * 0.1 }, className: `p-4 rounded-lg border transition-all cursor-pointer ${prayer.isCompleted
                        ? 'border-emerald-500/30 bg-emerald-500/10'
                        : 'border-slate-700 bg-slate-800/30 hover:border-slate-600'}`, onClick: () => !prayer.isCompleted && completePrayer(prayer.id), children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center space-x-4", children: [prayer.isCompleted ? (_jsx(CheckCircle, { className: "w-5 h-5 text-emerald-400" })) : (_jsx(Circle, { className: "w-5 h-5 text-slate-400" })), _jsxs("div", { children: [_jsxs("div", { className: "flex items-center space-x-3", children: [_jsx("h4", { className: "text-sm font-medium text-white", children: prayer.name }), _jsx("span", { className: "text-sm text-slate-400 font-arabic", children: prayer.arabicName })] }), _jsx("p", { className: "text-xs text-slate-400", children: prayer.time })] })] }), _jsxs("div", { className: "text-right", children: [prayer.isCompleted && prayer.completedAt && (_jsxs("div", { className: "text-xs text-emerald-400", children: ["\u2713 ", new Date(prayer.completedAt).toLocaleTimeString()] })), prayer.location && (_jsxs("div", { className: "flex items-center space-x-1 text-xs text-slate-400", children: [_jsx(MapPin, { className: "w-3 h-3" }), _jsx("span", { children: prayer.location })] }))] })] }), prayer.notes && (_jsxs("p", { className: "text-xs text-slate-400 mt-2 italic", children: ["\"", prayer.notes, "\""] }))] }, prayer.id))) }), _jsx("div", { className: "mt-6 flex space-x-3", children: _jsxs("button", { className: "flex-1 flex items-center justify-center space-x-2 py-2 bg-emerald-600 hover:bg-emerald-700 rounded-lg transition-colors", children: [_jsx(Plus, { className: "w-4 h-4 text-white" }), _jsx("span", { className: "text-white text-sm", children: "Add Prayer Note" })] }) }), _jsx("div", { className: "mt-6 p-3 bg-emerald-600/20 rounded-lg", children: _jsxs("p", { className: "text-sm text-emerald-300", children: ["\uD83D\uDD4C May Allah accept your prayers. ", completedPrayers > 0 ? 'Excellent consistency!' : 'Start with the next prayer time.'] }) })] }));
}
